---
- name: Patch and reboot servers
  hosts: "{{ limit | default('all') }}"
  vars:
    yum_name: "*"
    yum_state: latest
    bugfix_only: "{{ 'yes' if patch_type == 'bugfix' else 'no' }}"
    security_only: "{{ 'yes' if patch_type == 'security' else 'no' }}"
  tasks:

    - name: upgrade packages via yum
      yum:
        name={{ yum_name }}
        state={{ yum_state }}
        update_only=yes
        bugfix={{ bugfix_only }}
        security={{ security_only }}
      become: "yes"
      register: yumcommandout
      when:
        - (ansible_facts['distribution_major_version'] == '6') or
          (ansible_facts['distribution_major_version'] == '7')

    - name: Print errors if yum failed
      debug:
        msg: "yum command produced errors"
      when: yumcommandout is not defined
  
    - name: check to see if we need a reboot
      command: needs-restarting -r
      register: result
      ignore_errors: true
      changed_when: false

    - name: Reboot Server if Necessary
      reboot:
      when: result.rc == 1
    
    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 20
        sleep: 5
        delay: 5
        timeout: 300
